/**
 * brands.js
 * Source of truth for all BibleBooster production brands.
 *
 * Fields:
 *   key         — internal brand identifier (matches ibep-prod subdomain)
 *   flag        — emoji flag for the country
 *   country     — display name for the country / region
 *   org         — full organisation name
 *   tier        — "plus" | "essential" | "test"
 *   prodUrl     — internal production URL (ibep-prod.com)
 *   commercial  — public-facing commercial URL (empty string if unknown)
 *   logoUrl     — brand logo from Firebase storage
 */

const logo = (key) => `logos/${key}.png`;

const BRANDS = [
  {
    key:        "biblebooster",
    flag:       "🌍",
    country:    "BibleBooster",
    org:        "BibleBooster",
    tier:       "plus",
    prodUrl:    "https://biblebooster.ibep-prod.com/",
    commercial: "https://www.biblebooster.com/",
    logoUrl:    logo("biblebooster"),
  },
  {
    key:        "nbg",
    flag:       "🇳🇱",
    country:    "Netherlands",
    org:        "Nederlands Bijbelgenootschap",
    tier:       "plus",
    prodUrl:    "https://nbg.ibep-prod.com/",
    commercial: "https://www.debijbel.nl/",
    logoUrl:    logo("nbg"),
  },
  {
    key:        "abf",
    flag:       "🇫🇷",
    country:    "France",
    org:        "Alliance biblique française",
    tier:       "plus",
    prodUrl:    "https://abf.ibep-prod.com/",
    commercial: "https://lire.la-bible.net/",
    logoUrl:    logo("abf"),
  },
  {
    key:        "bsind",
    flag:       "🇮🇳",
    country:    "India",
    org:        "Bible Society of India",
    tier:       "plus",
    prodUrl:    "https://bsind.ibep-prod.com/",
    commercial: "https://www.indian.bible/",
    logoUrl:    logo("bsind"),
  },
  {
    key:        "bsl",
    flag:       "🇱🇹",
    country:    "Lithuania",
    org:        "Bible Society of Lithuania",
    tier:       "plus",
    prodUrl:    "https://bsl.ibep-prod.com/",
    commercial: "https://www.manobiblija.lt/",
    logoUrl:    logo("bsl"),
  },
  {
    key:        "bssa",
    flag:       "🇿🇦",
    country:    "South Africa",
    org:        "Bible Society of South Africa",
    tier:       "plus",
    prodUrl:    "https://bssa.ibep-prod.com/",
    commercial: "https://www.biblesa.co.za/",
    logoUrl:    logo("bssa"),
  },
  {
    key:        "ca",
    flag:       "🇨🇦",
    country:    "Canada",
    org:        "Canadian Bible Society",
    tier:       "plus",
    prodUrl:    "https://ca.ibep-prod.com/",
    commercial: "https://www.my-bible.ca/",
    logoUrl:    logo("ca"),
  },
  {
    key:        "diebibel",
    flag:       "🇩🇪",
    country:    "Germany",
    org:        "Deutsche Bibelgesellschaft",
    tier:       "plus",
    prodUrl:    "https://diebibel.ibep-prod.com/",
    commercial: "https://www.die-bibel.de/",
    logoUrl:    "logos/diebibel.svg",
  },
  {
    key:        "kor",
    flag:       "🇰🇷",
    country:    "Korea (alt)",
    org:        "Korea alt brand",
    tier:       "essential",
    prodUrl:    "https://kor.ibep-prod.com/",
    commercial: "https://bible.bskorea.or.kr/",
    logoUrl:    logo("kor"),
  },
  {
    key:        "sbarg",
    flag:       "🇦🇷",
    country:    "Argentina",
    org:        "Sociedad Bíblica Argentina",
    tier:       "plus",
    prodUrl:    "https://sbarg.ibep-prod.com/",
    commercial: "https://www.biblia.sba.org.ar/",
    logoUrl:    logo("sbarg"),
  },
  {
    key:        "sbb",
    flag:       "🇧🇷",
    country:    "Brazil",
    org:        "Sociedade Bíblica do Brasil",
    tier:       "plus",
    prodUrl:    "https://sbb.ibep-prod.com/",
    commercial: "https://www.sbb.org.br/",
    logoUrl:    logo("sbb"),
  },
  {
    key:        "sbp",
    flag:       "🇵🇹",
    country:    "Portugal",
    org:        "Sociedade Bíblica de Portugal",
    tier:       "plus",
    prodUrl:    "https://sbp.ibep-prod.com/",
    commercial: "https://www.biblia.pt/",
    logoUrl:    logo("sbp"),
  },
  {
    key:        "sbperu",
    flag:       "🇵🇪",
    country:    "Peru",
    org:        "Sociedade Bíblica del Perú",
    tier:       "plus",
    prodUrl:    "https://sbperu.ibep-prod.com/",
    commercial: "https://www.sbp.org.pe/",
    logoUrl:    logo("sbperu"),
  },
  {
    key:        "sbpy",
    flag:       "🇵🇾",
    country:    "Paraguay",
    org:        "Sociedad Bíblica Paraguaya",
    tier:       "essential",
    prodUrl:    "https://sbpy.ibep-prod.com/",
    commercial: "https://sbp.org.py/",
    logoUrl:    logo("sbpy"),
  },
  {
    key:        "sbs",
    flag:       "🇸🇪",
    country:    "Sweden",
    org:        "Svenska Bibelsällskapet",
    tier:       "plus",
    prodUrl:    "https://sbs.ibep-prod.com/",
    commercial: "https://www.bibeln.se/",
    logoUrl:    logo("sbs"),
  },
  {
    key:        "sp",
    flag:       "🇫🇮",
    country:    "Finland",
    org:        "Suomen Pipliaseura",
    tier:       "plus",
    prodUrl:    "https://sp.ibep-prod.com/",
    commercial: "https://www.raamattu.fi/",
    logoUrl:    logo("sp"),
  },
  {
    key:        "suriname",
    flag:       "🇸🇷",
    country:    "Suriname",
    org:        "Suriname Bible Society",
    tier:       "plus",
    prodUrl:    "https://suriname.ibep-prod.com/",
    commercial: "https://www.surinamebiblesoc.org/",
    logoUrl:    logo("suriname"),
  },
  // ── Essential community brands ────────────────────────────────────────────
  { key: "angola",           flag: "🇦🇴", country: "Angola",                      org: "Sociedade Bíblica de Angola",          tier: "essential", prodUrl: "https://sociedadebiblica.co.ao/",             commercial: "https://sociedadebiblica.co.ao/",             logoUrl: logo("angola") },
  { key: "botswana",         flag: "🇧🇼", country: "Botswana",                    org: "Bible Society of Botswana",            tier: "essential", prodUrl: "https://biblesociety-botswana.org/",           commercial: "https://biblesociety-botswana.org/",           logoUrl: logo("botswana") },
  { key: "chad",             flag: "🇹🇩", country: "Chad",                        org: "Alliance Biblique du Tchad",           tier: "essential", prodUrl: "https://alliancebiblique-tchad.org/",          commercial: "https://alliancebiblique-tchad.org/",          logoUrl: logo("chad") },
  { key: "ecuador",          flag: "🇪🇨", country: "Ecuador",                     org: "Sociedad Bíblica del Ecuador",         tier: "essential", prodUrl: "https://www.sbuec.org/",                      commercial: "https://www.sbuec.org/",                      logoUrl: logo("ecuador") },
  { key: "gambia",           flag: "🇬🇲", country: "Gambia",                      org: "Bible Society of Gambia",              tier: "essential", prodUrl: "https://biblesociety-gambia.org/",             commercial: "https://biblesociety-gambia.org/",             logoUrl: logo("gambia") },
  { key: "guinea",           flag: "🇬🇳", country: "Guinea",                      org: "Alliance Biblique de Guinée",          tier: "essential", prodUrl: "https://alliancebiblique-guinee.org/",          commercial: "https://alliancebiblique-guinee.org/",          logoUrl: logo("guinea") },
  { key: "ireland",          flag: "🇮🇪", country: "Ireland",                     org: "Bible Society in Ireland",             tier: "essential", prodUrl: "https://www.biblesocietyireland.ie/",           commercial: "https://www.biblesocietyireland.ie/",           logoUrl: logo("ireland") },
  { key: "latvia",           flag: "🇱🇻", country: "Latvia",                      org: "Latvijas Bībeles Biedrība",            tier: "essential", prodUrl: "https://bibele.bibelesbiedriba.lv/",           commercial: "https://bibele.bibelesbiedriba.lv/",           logoUrl: logo("latvia") },
  { key: "lesotho",          flag: "🇱🇸", country: "Lesotho",                     org: "Bible Society of Lesotho",             tier: "essential", prodUrl: "https://biblesociety.org.ls/",                 commercial: "https://biblesociety.org.ls/",                 logoUrl: logo("lesotho") },
  { key: "mali",             flag: "🇲🇱", country: "Mali",                        org: "Alliance Biblique du Mali",            tier: "essential", prodUrl: "https://alliancebiblique-mali.org/",            commercial: "https://alliancebiblique-mali.org/",            logoUrl: logo("mali") },
  { key: "namibia",          flag: "🇳🇦", country: "Namibia",                     org: "Bible Society of Namibia",             tier: "essential", prodUrl: "https://nambible.org.na/",                     commercial: "https://nambible.org.na/",                     logoUrl: logo("namibia") },
  { key: "nbv21",            flag: "🇳🇱", country: "Netherlands NBV21",           org: "NBV21",                                tier: "essential", prodUrl: "https://bijbel.nbv21.nl/",                     commercial: "https://bijbel.nbv21.nl/",                     logoUrl: logo("nbv21") },
  { key: "migrationbible",   flag: "🇳🇱", country: "Netherlands Migration Bible", org: "Migration Bible",                      tier: "essential", prodUrl: "https://migrationbible.com/",                  commercial: "https://migrationbible.com/",                  logoUrl: logo("migrationbible") },
  { key: "sciencebible",     flag: "🇳🇱", country: "Netherlands Science Bible",   org: "Wetenschapsbijbel",                    tier: "essential", prodUrl: "http://wetenschapsbijbel.bijbelgenootschap.nl/", commercial: "http://wetenschapsbijbel.bijbelgenootschap.nl/", logoUrl: logo("sciencebible") },
  { key: "niger",            flag: "🇳🇪", country: "Niger",                       org: "Alliance Biblique du Niger",           tier: "essential", prodUrl: "https://alliancebiblique-niger.org/",           commercial: "https://alliancebiblique-niger.org/",           logoUrl: logo("niger") },
  { key: "palestine",        flag: "🇵🇸", country: "Palestine",                   org: "Palestine Bible Society",              tier: "essential", prodUrl: "https://ar.pbs-web.org/",                      commercial: "https://ar.pbs-web.org/",                      logoUrl: logo("palestine") },
  { key: "palestinediaspora",flag: "🇵🇸", country: "Palestine Diaspora",          org: "Palestine Bible Society Diaspora",     tier: "essential", prodUrl: "https://www.pbs-web.org/",                     commercial: "https://www.pbs-web.org/",                     logoUrl: logo("palestinediaspora") },
  { key: "poland",           flag: "🇵🇱", country: "Poland",                      org: "Bible Society of Poland",              tier: "essential", prodUrl: "https://poland.ibep-se.com/",                  commercial: "https://poland.ibep-se.com/",                  logoUrl: logo("poland") },
  { key: "romania",          flag: "🇷🇴", country: "Romania",                     org: "Societatea Biblică din România",       tier: "essential", prodUrl: "https://societateabiblica.org/",               commercial: "https://societateabiblica.org/",               logoUrl: logo("romania") },
  { key: "senegal",          flag: "🇸🇳", country: "Senegal",                     org: "Alliance Biblique du Sénégal",         tier: "essential", prodUrl: "https://alliancebiblique-senegal.org/",         commercial: "https://alliancebiblique-senegal.org/",         logoUrl: logo("senegal") },
  { key: "southsudan",       flag: "🇸🇸", country: "South Sudan",                 org: "Bible Society of South Sudan",         tier: "essential", prodUrl: "https://biblesociety-southsudan.org/",          commercial: "https://biblesociety-southsudan.org/",          logoUrl: logo("southsudan") },
  { key: "sudan",            flag: "🇸🇩", country: "Sudan",                       org: "Bible Society of Sudan",               tier: "essential", prodUrl: "https://biblesociety-sudan.org/",               commercial: "https://biblesociety-sudan.org/",               logoUrl: logo("sudan") },
  { key: "ukraine",          flag: "🇺🇦", country: "Ukraine",                     org: "Ukrainian Bible Society",              tier: "essential", prodUrl: "https://www.ukrbs.org/",                       commercial: "https://www.ukrbs.org/",                       logoUrl: logo("ukraine") },

  {
    key:        "testbrand",
    flag:       "🧪",
    country:    "Test",
    org:        "Test Brand",
    tier:       "test",
    prodUrl:    "https://testbrand.ibep-prod.com/",
    commercial: "",
    logoUrl:    logo("testbrand"),
  },
  {
    key:        "zwe",
    flag:       "🇿🇼",
    country:    "Zimbabwe",
    org:        "Bible Society of Zimbabwe",
    tier:       "essential",
    prodUrl:    "https://zwe.ibep-prod.com/",
    commercial: "https://biblesociety-zimbabwe.org/",
    logoUrl:    logo("zwe"),
  },
];
