/**
 * brands.js
 * Source of truth for all BibleBooster production brands.
 *
 * Fields:
 *   key         — internal brand identifier (matches ibep-prod subdomain)
 *   flag        — emoji flag for the country
 *   country     — display name for the country / region
 *   org         — full organisation name
 *   tier        — "plus" | "essential" | "test"
 *   prodUrl     — internal production URL (ibep-prod.com)
 *   commercial  — public-facing commercial URL (empty string if unknown)
 */

const BRANDS = [
  {
    key:        "nbg",
    flag:       "🇳🇱",
    country:    "Netherlands",
    org:        "Nederlands Bijbelgenootschap",
    tier:       "plus",
    prodUrl:    "https://nbg.ibep-prod.com/",
    commercial: "https://debijbel.nl/",
  },
  {
    key:        "abf",
    flag:       "🇧🇷",
    country:    "Brazil",
    org:        "ABF",
    tier:       "essential",
    prodUrl:    "https://abf.ibep-prod.com/",
    commercial: "",
  },
  {
    key:        "biblebooster",
    flag:       "🌍",
    country:    "Global",
    org:        "BibleBooster",
    tier:       "plus",
    prodUrl:    "https://biblebooster.ibep-prod.com/",
    commercial: "https://biblebooster.ibep-prod.com/",
  },
  {
    key:        "bsind",
    flag:       "🇮🇳",
    country:    "India",
    org:        "Bible Society of India",
    tier:       "plus",
    prodUrl:    "https://bsind.ibep-prod.com/",
    commercial: "https://www.indian.bible/",
  },
  {
    key:        "bsk",
    flag:       "🇰🇷",
    country:    "South Korea",
    org:        "Bible Society of Korea",
    tier:       "plus",
    prodUrl:    "https://bsk.ibep-prod.com/",
    commercial: "https://bible.bskorea.or.kr/",
  },
  {
    key:        "bsl",
    flag:       "🇱🇹",
    country:    "Lithuania",
    org:        "Bible Society of Lithuania",
    tier:       "plus",
    prodUrl:    "https://bsl.ibep-prod.com/",
    commercial: "https://manobiblija.lt/",
  },
  {
    key:        "bsrus",
    flag:       "🇷🇺",
    country:    "Russia",
    org:        "Bible Society of Russia",
    tier:       "essential",
    prodUrl:    "https://bsrus.ibep-prod.com/",
    commercial: "",
  },
  {
    key:        "bssa",
    flag:       "🇿🇦",
    country:    "South Africa",
    org:        "Bible Society of South Africa",
    tier:       "plus",
    prodUrl:    "https://bssa.ibep-prod.com/",
    commercial: "https://www.biblesa.co.za/",
  },
  {
    key:        "ca",
    flag:       "🇨🇦",
    country:    "Canada",
    org:        "Canadian Bible Society",
    tier:       "plus",
    prodUrl:    "https://ca.ibep-prod.com/",
    commercial: "https://www.my-bible.ca/",
  },
  {
    key:        "diebibel",
    flag:       "🇩🇪",
    country:    "Germany",
    org:        "Deutsche Bibelgesellschaft",
    tier:       "plus",
    prodUrl:    "https://diebibel.ibep-prod.com/",
    commercial: "https://www.die-bibel.de/",
  },
  {
    key:        "kor",
    flag:       "🇰🇷",
    country:    "Korea (alt)",
    org:        "Korea alt brand",
    tier:       "essential",
    prodUrl:    "https://kor.ibep-prod.com/",
    commercial: "",
  },
  {
    key:        "sbarg",
    flag:       "🇦🇷",
    country:    "Argentina",
    org:        "Sociedad Bíblica Argentina",
    tier:       "plus",
    prodUrl:    "https://sbarg.ibep-prod.com/",
    commercial: "https://biblia.sba.org.ar/",
  },
  {
    key:        "sbb",
    flag:       "🇧🇷",
    country:    "Brazil",
    org:        "Sociedade Bíblica do Brasil",
    tier:       "plus",
    prodUrl:    "https://sbb.ibep-prod.com/",
    commercial: "https://sbb.org.br/",
  },
  {
    key:        "sbp",
    flag:       "🇵🇹",
    country:    "Portugal",
    org:        "Sociedade Bíblica de Portugal",
    tier:       "plus",
    prodUrl:    "https://sbp.ibep-prod.com/",
    commercial: "https://biblia.pt/",
  },
  {
    key:        "sbperu",
    flag:       "🇵🇪",
    country:    "Peru",
    org:        "Sociedade Bíblica del Perú",
    tier:       "plus",
    prodUrl:    "https://sbperu.ibep-prod.com/",
    commercial: "https://www.sbp.org.pe/",
  },
  {
    key:        "sbpy",
    flag:       "🇵🇾",
    country:    "Paraguay",
    org:        "Sociedad Bíblica Paraguaya",
    tier:       "essential",
    prodUrl:    "https://sbpy.ibep-prod.com/",
    commercial: "https://sbp.org.py/",
  },
  {
    key:        "sbs",
    flag:       "🇸🇪",
    country:    "Sweden",
    org:        "Svenska Bibelsällskapet",
    tier:       "plus",
    prodUrl:    "https://sbs.ibep-prod.com/",
    commercial: "https://www.bibeln.se/",
  },
  {
    key:        "sp",
    flag:       "🇫🇮",
    country:    "Finland",
    org:        "Suomen Pipliaseura",
    tier:       "plus",
    prodUrl:    "https://sp.ibep-prod.com/",
    commercial: "https://raamattu.fi/",
  },
  {
    key:        "suriname",
    flag:       "🇸🇷",
    country:    "Suriname",
    org:        "Suriname Bible Society",
    tier:       "plus",
    prodUrl:    "https://suriname.ibep-prod.com/",
    commercial: "https://surinamebiblesoc.org/",
  },
  {
    key:        "testbrand",
    flag:       "🧪",
    country:    "Test",
    org:        "Test Brand",
    tier:       "test",
    prodUrl:    "https://testbrand.ibep-prod.com/",
    commercial: "",
  },
  {
    key:        "zwe",
    flag:       "🇿🇼",
    country:    "Zimbabwe",
    org:        "Bible Society of Zimbabwe",
    tier:       "essential",
    prodUrl:    "https://zwe.ibep-prod.com/",
    commercial: "https://biblesociety-zimbabwe.org/",
  },
];
